server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: enxryl-gateway

  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://ENXRYL-SECURITY
          predicates:
            - Path=/security/**
          filters:
            - RewritePath=/security/(?<segment>.*),/api/$\{segment}

        - id: storage-service
          uri: lb://ENXRYL-STORAGE
          predicates:
            - Path=/storage/**
          filters:
            - RewritePath=/storage/(?<segment>.*),/api/$\{segment}
            - name: RequestHeader

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG